spring:
  application:
    name: ai-lowcode
  profiles:
    active: local # 启动时会自动加载两个配置文件，application-local.yaml中的配置会覆盖同名属性。
  # mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ai-lowcode
  # redis
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      password:
      ttl: 3600 # 过期时间
  # session
  session:
    store-type: redis
    timeout: 2592000 # session 30 天过期
server:
  port: 8123
  servlet:
    context-path: /api
    session:
      cookie:
        max-age: 2592000
# springdoc-openapi
springdoc:
  group-configs:
    - group: 'default'
      packages-to-scan: com.hex.ailowcode.controller
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn
# AI
langchain4j:
  open-ai:
    chat-model:
      max-tokens: 8192 # 设置最大输出token上限，防止截断
      strict-json-schema: true # 设置模型响应严格为JSON格式
      response-format: json_object
# Actuator配置，暴露监控端点
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always
